spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sample?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: iamchenjie
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: rabbit
    password: rabbit
  cloud:
    stream:
      bindings:
        user_log:
          consumer:
            max-attempts: 1
          content-type: application/json
          destination: user_log
          group: g1
        user_log_producer:
          content-type: application/json
          destination: user_log
      rabbit:
        bindings:
          user_log:
            consumer:
              auto-bind-dlq: true
              dlq-dead-letter-exchange:
              dlq-ttl: 5000
  sleuth:
    sampler:
      percentage: 1

mybatis:
  mapper-locations: classpath*:/user-mapper/*Mapper.xml